PE-D Bug Fixing 1
AY2324S1-CS2113-W12-2/tp pull request #107
Opened 2023-11-04 04:27 UTC by danielpappa

closes #84
closes #86
closes #96 
closes #99 
closes #100
closes #104 
closes #105

2023-11-05 13:05 UTC, mcmc101001 approved these changes
LGTM

2023-11-05 13:05 UTC, mcmc101001 commented on docs/UserGuide.md
should this be `java -jar CashLeh.jar ` instead?

2023-11-05 13:05 UTC, mcmc101001 commented on docs/UserGuide.md
> +Format: `addExpense DESCRIPTION /amt AMOUNT /date DATE /cat CATEGORY`
good catch!

2023-11-05 13:47 UTC, mcmc101001 requested changes
Modify UG to `java -jar CashLeh.jar `

2023-11-06 03:19 UTC, BenedictChannn approved these changes
LGTM

2023-11-06 03:20 UTC, mcmc101001 approved these changes
LGTM

2023-11-06 03:21 UTC, merged