PPP Draft
AY2324S1-CS2113-W12-2/tp pull request #114
Opened 2023-11-07 12:45 UTC by danielpappa

Created PPP, updated some diagrams and cleaned UG, DG and main page

2023-11-07 13:02 UTC, BenedictChannn approved these changes
LGTM

2023-11-07 13:02 UTC, BenedictChannn commented on docs/UserGuide.md
> +Change the password in case you believe your previous one may have been leaked.
Clear elaboration

2023-11-07 13:02 UTC, BenedictChannn commented on docs/team/danielpappalardo.md
> +  * Helped maintaining the issue tracker on GitHub
I believe "maintain" is more appropriate

2023-11-08 11:14 UTC, mcmc101001 requested changes

2023-11-08 11:14 UTC, mcmc101001 commented on docs/AboutUs.md
> +| ![](https://via.placeholder.com/100.png?text=Photo)  |     Ming Chun     | [Github](https://github.com/mcmc101001)       | [Portfolio](docs/team/mcmc101001.md) |
i don't think need docs as everyone else does not

2023-11-08 17:01 UTC, mcmc101001 approved these changes
LGTM

2023-11-08 17:01 UTC, merged