Modify Expense class and implement JUnit testing
AY2324S1-CS2113-W12-2/tp pull request #32
Opened 2023-10-16 04:05 UTC by WooKaiNing

2023-10-18 07:20 UTC, mcmc101001 requested changes
I think we should fix merge conflicts first

2023-10-18 17:02 UTC, mcmc101001 approved these changes
LGTM

2023-10-18 20:37 UTC, WooKaiNing commented
Modified input.txt to only include expense/income that have a fixed date for now, as dynamic updating of EXPECTED.TXT is required for expense/income without date input -> have implemented a CurrentDate class that will write to the EXPECTED.TXT file to update placeholder to current date, but this only works on macos and ubuntu after updating runtest.sh().

not sure if its bc i didn't modify runtest.bat correctly, thus doesnt work for windows

2023-10-19 04:09 UTC, WooKaiNing commented
Implemented CurrentDateUpdater class to dynamically update EXPECTED.TXT file with current date (for input in INPUT.TXT where date is not specified). However, this somehow only works for Java CI / build (ubuntu-latest) (pull_request) and Java CI / build (macos-latest) (pull_request).

Hence, modified input.txt to only include expense/income input with specified date for now, will need to further refine code such that runtest.bat() works too.

2023-10-19 09:00 UTC, mcmc101001 approved these changes

2023-10-19 13:26 UTC, danielpappa approved these changes

2023-10-19 13:26 UTC, danielpappa commented on src/main/java/cashleh/CurrentDateUpdater.java
Great thinking and nice implementation.

2023-10-19 13:26 UTC, danielpappa commented on src/main/java/cashleh/CurrentDateUpdater.java
> +        List<String> updatedLines = lines.stream()
Great coding!

2023-10-19 13:29 UTC, WooKaiNing commented
Fixes #45

2023-10-19 13:38 UTC, merged